### ISSUE TITLE
Rename your files

### ISSUE THREAD

**Issue by Josephenoch** [GabieRise/login-page#1]
Ensure all your files have a relevant and appropriate name. Here, you have one html file, so it should be index.html

**Comment by GabieRise** [comment]
Alright thanks



Sent from App for Gmail


Saturday, 16 July 2022, 21:06 +0100 from ***@***.***  ***@***.***>:

**Comment by GabieRise** [comment]
>

**Comment by GabieRise** [comment]
Done
